# Generated by Django 3.1 on 2020-08-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fzm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='type',
        ),
    ]
