# Generated by Django 3.1 on 2020-08-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fzm', '0003_auto_20200828_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockoperate',
            name='operate_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
