# Generated by Django 3.1 on 2020-09-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fzm', '0004_auto_20200831_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoperate',
            name='note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
